map $host $cors_allow_origin {
    default "https://adnull.com";
    #"https://docs.adnull.com";
}

server {
    server_name docs.adnull.com www.docs.adnull.com;

    if ($host = www.docs.adnull.com) {
      return 301 https://docs.adnull.com$request_uri;
    }

    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /home/deploy/chatwoot/public;

    # CORS
    add_header Access-Control-Allow-Origin $cors_allow_origin always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-Requested-With" always;
    add_header Access-Control-Expose-Headers "ETag, Last-Modified, Cache-Control, Content-Type" always;
    add_header Vary "Origin" always;

    # Turn on Passenger
    passenger_enabled on;
    passenger_ruby /usr/share/rvm/gems/ruby-3.4.4@chatwoot/wrappers/ruby;
    #passenger_sticky_sessions on;
    client_max_body_size 20M;

    # Cable config
    location /cable {
        passenger_app_group_name donateraiser_action_cable;
        passenger_force_max_concurrent_requests_per_process 0;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/docs.adnull.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/docs.adnull.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    if ($host = www.docs.adnull.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host ~ ^[^.]+\.docs.adnull\.com$) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = docs.adnull.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name docs.adnull.com www.docs.adnull.com;
    listen 80;
    return 404; # managed by Certbot



}

server {
    if ($host = docs.adnull.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name docs.adnull.com www.docs.adnull.com;
    listen 80;
    return 404; # managed by Certbot
